import sqlite3
import pandas as pd
from fpdf import FPDF
from typing import Dict, Any

def generate_pdf_report(prediction_data: Dict[str, Any], filepath: str):
    pdf = FPDF()
    pdf.add_page()
    
    # Title Header
    pdf.set_font("Helvetica", "B", 20)
    pdf.set_text_color(0, 229, 255)
    pdf.cell(0, 15, "SONAR AI - Object Detection Report", ln=True, align="C")
    
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 8, "Generated by SONAR AI Autonomous Defense Platform v2.0", ln=True, align="C")
    pdf.ln(10)
    
    # Prediction Result Banner
    pred = prediction_data.get("prediction", "Unknown")
    conf = prediction_data.get("confidence", 0.0)
    model_used = prediction_data.get("model_used", "Random Forest")

    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(255, 255, 255)
    
    if pred == "Mine":
        pdf.set_fill_color(255, 77, 109) # Danger Red
    else:
        pdf.set_fill_color(0, 255, 148) # Success Green
        
    pdf.cell(0, 12, f"CLASSIFICATION: {pred.upper()} ({conf}% Confidence)", ln=True, align="C", fill=True)
    pdf.ln(8)
    
    # Model Metadata Table
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(60, 8, "Model Architecture:", border=0)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, model_used, ln=True)

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(60, 8, "Sonar Signal Resolution:", border=0)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, "60 Frequency Channels", ln=True)
    pdf.ln(8)
    
    # Feature Attribution
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Top Signal Attributions (XAI Feature Importance):", ln=True)
    pdf.set_font("Helvetica", "", 10)
    
    top_features = prediction_data.get("top_features", [])
    for item in top_features:
        name = item.get("feature", "Signal")
        val = item.get("value", 0.0)
        imp = item.get("importance", 0.0)
        pdf.cell(0, 6, f"- {name}: Value = {val:.4f} | Contribution = {imp}%", ln=True)
        
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 5, "Notice: This automated report is generated by SONAR AI based on high-frequency acoustic reflection patterns. Confidential sonar analysis data.")
    
    pdf.output(filepath)
